# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
   config.vm.define :centos_server do |server|
    server.vm.box = "centos_rabbit"
    server.vm.network :private_network, ip: "192.168.56.101"
    #server.vm.network "public_network", bridge: "eno1", ip:"192.168.131.125", netmask: "255.255.255.0"
    server.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024","--cpus", "1", "--name", "centos_services" ]
    end
    server.vm.provision "shell", path: "server.sh"
  end
  config.vm.define :centos_serviceA do |serviceA|
    serviceA.vm.box = "centos_rabbit"
    serviceA.vm.network :private_network, ip: "192.168.56.102"
    #serviceA.vm.network "public_network", bridge: "eno1", ip:"192.168.131.101", netmask: "255.255.255.0"
    serviceA.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "256","--cpus", "1", "--name", "centos_serviceA" ]
    end
    serviceA.vm.provision "shell", path: "serviceA.sh"
  end
end


